version: 2

sources:
  - name: thorchain_midgard
    database: HEVO
    schema: THORCHAIN_MIDGARD_2_24_2_NEW
    tables:
      - name: midgard_active_vault_events
      - name: midgard_add_events
      - name: midgard_asgard_fund_yggdrasil_events
      - name: midgard_block_log
      - name: midgard_block_pool_depths
      - name: midgard_bond_events
      - name: bond_events_pk_count
      - name: midgard_constants
      - name: midgard_errata_events
      - name: midgard_fee_events
      - name: fee_events_pk_count
      - name: midgard_gas_events
      - name: midgard_inactive_vault_events
      - name: midgard_loan_open_events
      - name: midgard_loan_repayment_events
      - name: midgard_message_events
      - name: midgard_mint_burn_events
      - name: midgard_network_version_events
      - name: midgard_new_node_events
      - name: midgard_outbound_events
      - name: midgard_pending_liquidity_events
      - name: midgard_pool_balance_change_events
      - name: midgard_pool_events
      - name: midgard_refund_events
      - name: midgard_reserve_events
      - name: midgard_rewards_event_entries
      - name: midgard_rewards_events
      - name: midgard_rune_pool_deposit_events
      - name: midgard_rune_pool_withdraw_events
      - name: midgard_rune_price
      - name: midgard_scheduled_outbound_events
      - name: midgard_send_messages
      - name: midgard_set_ip_address_events
      - name: midgard_set_mimir_events
      - name: midgard_set_node_keys_events
      - name: midgard_set_version_events
      - name: midgard_slash_events
      - name: midgard_slash_points_events
      - name: midgard_stake_events
      - name: midgard_streaming_swap_details_events
      - name: midgard_swap_events
      - name: midgard_switch_events
      - name: switch_events_pk_count
      - name: midgard_thorname_change_events
      - name: midgard_trade_account_deposit_events
      - name: midgard_trade_account_withdraw_events
      - name: midgard_transfer_events
      - name: midgard_tss_keygen_failure_events
      - name: midgard_tss_keygen_success_events
      - name: midgard_unstake_events
      - name: midgard_update_node_account_status_events
      - name: midgard_validator_request_leave_events
      - name: midgard_withdraw_events
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'THORCHAIN' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
  - name: silver_crosschain
    database: "{{ 'crosschain' if target.database == 'BITCOIN' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: github_actions
    database: thorchain
    schema: github_actions
    tables:
      - name: workflows
