version: 2

sources:
  - name: shared
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
  - name: thorchain_midgard
    database: HEVO
    schema: THORCHAIN_MIDGARD_2_10
    tables:
      - name: midgard_active_vault_events
      - name: midgard_add_events
      - name: midgard_asgard_fund_yggdrasil_events
      - name: midgard_block_log
      - name: midgard_block_pool_depths
      - name: midgard_bond_events
      - name: bond_events_pk_count
      - name: midgard_constants
      - name: midgard_errata_events
      - name: midgard_fee_events
      - name: fee_events_pk_count
      - name: midgard_gas_events
      - name: midgard_inactive_vault_events
      - name: midgard_message_events
      - name: midgard_new_node_events
      - name: midgard_outbound_events
      - name: midgard_pending_liquidity_events
      - name: midgard_pool_balance_change_events
      - name: midgard_pool_events
      - name: midgard_refund_events
      - name: midgard_reserve_events
      - name: midgard_rewards_event_entries
      - name: midgard_rewards_events
      - name: midgard_set_ip_address_events
      - name: midgard_set_mimir_events
      - name: midgard_set_node_keys_events
      - name: midgard_set_version_events
      - name: midgard_slash_events
      - name: midgard_slash_points_events
      - name: midgard_stake_events
      - name: midgard_swap_events
      - name: midgard_switch_events
      - name: switch_events_pk_count
      - name: midgard_thorname_change_events
      - name: midgard_transfer_events
      - name: midgard_unstake_events
      - name: midgard_update_node_account_status_events
      - name: midgard_validator_request_leave_events
      - name: midgard_withdraw_events
  - name: crosschain
    database: flipside_prod_db
    schema: silver_crosschain
    tables:
      - name: address_labels
